# -*- coding: utf-8 -*-
"""Natalia_Amaral_aula17Pratico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W_EsPUxI3UYiIVi02JITbV7J8bN2P7pu

Para o dataset: http://cs.joensuu.fi/sipu/datasets/Aggregation.txt
"""

# Importação das bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import rand_score

# Configurações. Aqui coloquei k até 6, pois sabemos que o ideal são 2 grupos, mas quis que o algoritmo decidisse isso.
url = "http://cs.joensuu.fi/sipu/datasets/Aggregation.txt"
valores_k = [2, 3, 4, 5, 6, 7, 8, 9, 10]
limiar_convergencia = 0.0001

# Carregamento dos dados ignorando a terceira coluna, pois aqui o aprendizado é não supervisionado.
df = pd.read_csv(url, sep= r'\s+', header=None)
X = df.iloc[:, [0, 1]].values
y_real = df.iloc[:, 2].values

# Variáveis para lembrar o melhor resultado de cada algoritmo
melhor_k_kmeans = 0
melhor_nota_kmeans = -1
melhores_labels_kmeans = []

melhor_k_single = 0
melhor_nota_single = -1
melhores_labels_single = []

# Testa todos os valores de k para ambos os algoritmos
for k in valores_k:

    kmeans = KMeans(n_clusters=k, tol=limiar_convergencia, random_state=42)
    labels_km = kmeans.fit_predict(X)
    nota_km = rand_score(y_real, labels_km)

    # Se a nota atual for maior que a nota guardada, atualizamos a memória
    if nota_km > melhor_nota_kmeans:
        melhor_nota_kmeans = nota_km
        melhor_k_kmeans = k
        melhores_labels_kmeans = labels_km

    single_linkage = AgglomerativeClustering(n_clusters=k, linkage='single')
    labels_sg = single_linkage.fit_predict(X)
    nota_sg = rand_score(y_real, labels_sg)

    # Se a nota atual for maior que a nota guardada, atualizamos a memória
    if nota_sg > melhor_nota_single:
        melhor_nota_single = nota_sg
        melhor_k_single = k
        melhores_labels_single = labels_sg

# Exibe os melhores resultados para o k encontrado
print("Melhor resultado:")
print(f"K-Means (Melhor K = {melhor_k_kmeans}):        {melhor_nota_kmeans:.4f}")
print(f"Single Linkage (Melhor K = {melhor_k_single}): {melhor_nota_single:.4f}")
print("-------------------------------------------")

# Plota os gráficos que obtiveram os melhores resultados para cada algoritmo
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))


ax1.scatter(X[:, 0], X[:, 1], c=melhores_labels_kmeans, cmap='viridis', s=15)
ax1.set_title(f"K-Means (K={melhor_k_kmeans}) | Índice Rand: {melhor_nota_kmeans:.2f}")
ax1.set_xlabel("Eixo X")
ax1.set_ylabel("Eixo Y")


ax2.scatter(X[:, 0], X[:, 1], c=melhores_labels_single, cmap='plasma', s=15)
ax2.set_title(f"Single Linkage (K={melhor_k_single}) | Índice Rand: {melhor_nota_single:.2f}")
ax2.set_xlabel("Eixo X")
ax2.set_ylabel("Eixo Y")

plt.show()

"""Sabemos que o ideal são 7 grupos, vamos ver o que acontece quando colocamos k = 7"""

# Importação das bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import rand_score

# Configurações. Aqui coloquei k até 6, pois sabemos que o ideal são 2 grupos, mas quis que o algoritmo decidisse isso.
url = "http://cs.joensuu.fi/sipu/datasets/Aggregation.txt"
valores_k = [7]
limiar_convergencia = 0.0001

# Carregamento dos dados ignorando a terceira coluna, pois aqui o aprendizado é não supervisionado.
df = pd.read_csv(url, sep= r'\s+', header=None)
X = df.iloc[:, [0, 1]].values
y_real = df.iloc[:, 2].values

# Variáveis para lembrar o melhor resultado de cada algoritmo
melhor_k_kmeans = 0
melhor_nota_kmeans = -1
melhores_labels_kmeans = []

melhor_k_single = 0
melhor_nota_single = -1
melhores_labels_single = []

# Testa todos os valores de k para ambos os algoritmos
for k in valores_k:

    kmeans = KMeans(n_clusters=k, tol=limiar_convergencia, random_state=42)
    labels_km = kmeans.fit_predict(X)
    nota_km = rand_score(y_real, labels_km)

    # Se a nota atual for maior que a nota guardada, atualizamos a memória
    if nota_km > melhor_nota_kmeans:
        melhor_nota_kmeans = nota_km
        melhor_k_kmeans = k
        melhores_labels_kmeans = labels_km

    single_linkage = AgglomerativeClustering(n_clusters=k, linkage='single')
    labels_sg = single_linkage.fit_predict(X)
    nota_sg = rand_score(y_real, labels_sg)

    # Se a nota atual for maior que a nota guardada, atualizamos a memória
    if nota_sg > melhor_nota_single:
        melhor_nota_single = nota_sg
        melhor_k_single = k
        melhores_labels_single = labels_sg

# Exibe os melhores resultados para o k encontrado
print("Melhor resultado:")
print(f"K-Means (Melhor K = {melhor_k_kmeans}):        {melhor_nota_kmeans:.4f}")
print(f"Single Linkage (Melhor K = {melhor_k_single}): {melhor_nota_single:.4f}")
print("-------------------------------------------")

# Plota os gráficos que obtiveram os melhores resultados para cada algoritmo
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))


ax1.scatter(X[:, 0], X[:, 1], c=melhores_labels_kmeans, cmap='viridis', s=15)
ax1.set_title(f"K-Means (K={melhor_k_kmeans}) | Índice Rand: {melhor_nota_kmeans:.2f}")
ax1.set_xlabel("Eixo X")
ax1.set_ylabel("Eixo Y")


ax2.scatter(X[:, 0], X[:, 1], c=melhores_labels_single, cmap='plasma', s=15)
ax2.set_title(f"Single Linkage (K={melhor_k_single}) | Índice Rand: {melhor_nota_single:.2f}")
ax2.set_xlabel("Eixo X")
ax2.set_ylabel("Eixo Y")

plt.show()

"""Para o dataset: http://cs.joensuu.fi/sipu/datasets/D31.txt"""

# Importação das bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import rand_score

# Configurações. Aqui coloquei k variando entre 25 a 35, pois sabemos que o ideal são 31 grupos, mas quis que o algoritmo decidisse isso.
url = "http://cs.joensuu.fi/sipu/datasets/D31.txt"
valores_k = [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]
limiar_convergencia = 0.0001

# Carregamento dos dados ignorando a terceira coluna, pois aqui o aprendizado é não supervisionado.
df = pd.read_csv(url, sep= r'\s+', header=None)
X = df.iloc[:, [0, 1]].values
y_real = df.iloc[:, 2].values

# Variáveis para lembrar o melhor resultado de cada algoritmo
melhor_k_kmeans = 0
melhor_nota_kmeans = -1
melhores_labels_kmeans = []

melhor_k_single = 0
melhor_nota_single = -1
melhores_labels_single = []

# Testa todos os valores de k para ambos os algoritmos
for k in valores_k:

    kmeans = KMeans(n_clusters=k, tol=limiar_convergencia, random_state=42)
    labels_km = kmeans.fit_predict(X)
    nota_km = rand_score(y_real, labels_km)

    # Se a nota atual for maior que a nota guardada, atualizamos a memória
    if nota_km > melhor_nota_kmeans:
        melhor_nota_kmeans = nota_km
        melhor_k_kmeans = k
        melhores_labels_kmeans = labels_km

    single_linkage = AgglomerativeClustering(n_clusters=k, linkage='single')
    labels_sg = single_linkage.fit_predict(X)
    nota_sg = rand_score(y_real, labels_sg)

    # Se a nota atual for maior que a nota guardada, atualizamos a memória
    if nota_sg > melhor_nota_single:
        melhor_nota_single = nota_sg
        melhor_k_single = k
        melhores_labels_single = labels_sg

# Exibe os melhores resultados para o k encontrado
print("Melhor resultado:")
print(f"K-Means (Melhor K = {melhor_k_kmeans}):        {melhor_nota_kmeans:.4f}")
print(f"Single Linkage (Melhor K = {melhor_k_single}): {melhor_nota_single:.4f}")
print("-------------------------------------------")

# Plota os gráficos que obtiveram os melhores resultados para cada algoritmo
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))


ax1.scatter(X[:, 0], X[:, 1], c=melhores_labels_kmeans, cmap='viridis', s=15)
ax1.set_title(f"K-Means (K={melhor_k_kmeans}) | Índice Rand: {melhor_nota_kmeans:.2f}")
ax1.set_xlabel("Eixo X")
ax1.set_ylabel("Eixo Y")


ax2.scatter(X[:, 0], X[:, 1], c=melhores_labels_single, cmap='plasma', s=15)
ax2.set_title(f"Single Linkage (K={melhor_k_single}) | Índice Rand: {melhor_nota_single:.2f}")
ax2.set_xlabel("Eixo X")
ax2.set_ylabel("Eixo Y")

plt.show()

"""Sabemos que o ideal seriam 31 grupos, então vamos testar para k =31"""

# Importação das bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import rand_score

# Configurações. Aqui coloquei k variando entre 25 a 35, pois sabemos que o ideal são 31 grupos, mas quis que o algoritmo decidisse isso.
url = "http://cs.joensuu.fi/sipu/datasets/D31.txt"
valores_k = [31]
limiar_convergencia = 0.0001

# Carregamento dos dados ignorando a terceira coluna, pois aqui o aprendizado é não supervisionado.
df = pd.read_csv(url, sep= r'\s+', header=None)
X = df.iloc[:, [0, 1]].values
y_real = df.iloc[:, 2].values

# Variáveis para lembrar o melhor resultado de cada algoritmo
melhor_k_kmeans = 0
melhor_nota_kmeans = -1
melhores_labels_kmeans = []

melhor_k_single = 0
melhor_nota_single = -1
melhores_labels_single = []

# Testa todos os valores de k para ambos os algoritmos
for k in valores_k:

    kmeans = KMeans(n_clusters=k, tol=limiar_convergencia, random_state=42)
    labels_km = kmeans.fit_predict(X)
    nota_km = rand_score(y_real, labels_km)

    # Se a nota atual for maior que a nota guardada, atualizamos a memória
    if nota_km > melhor_nota_kmeans:
        melhor_nota_kmeans = nota_km
        melhor_k_kmeans = k
        melhores_labels_kmeans = labels_km

    single_linkage = AgglomerativeClustering(n_clusters=k, linkage='single')
    labels_sg = single_linkage.fit_predict(X)
    nota_sg = rand_score(y_real, labels_sg)

    # Se a nota atual for maior que a nota guardada, atualizamos a memória
    if nota_sg > melhor_nota_single:
        melhor_nota_single = nota_sg
        melhor_k_single = k
        melhores_labels_single = labels_sg

# Exibe os melhores resultados para o k encontrado
print("Melhor resultado:")
print(f"K-Means (Melhor K = {melhor_k_kmeans}):        {melhor_nota_kmeans:.4f}")
print(f"Single Linkage (Melhor K = {melhor_k_single}): {melhor_nota_single:.4f}")
print("-------------------------------------------")

# Plota os gráficos que obtiveram os melhores resultados para cada algoritmo
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))


ax1.scatter(X[:, 0], X[:, 1], c=melhores_labels_kmeans, cmap='viridis', s=15)
ax1.set_title(f"K-Means (K={melhor_k_kmeans}) | Índice Rand: {melhor_nota_kmeans:.2f}")
ax1.set_xlabel("Eixo X")
ax1.set_ylabel("Eixo Y")


ax2.scatter(X[:, 0], X[:, 1], c=melhores_labels_single, cmap='plasma', s=15)
ax2.set_title(f"Single Linkage (K={melhor_k_single}) | Índice Rand: {melhor_nota_single:.2f}")
ax2.set_xlabel("Eixo X")
ax2.set_ylabel("Eixo Y")

plt.show()

"""Para o dataset: http://cs.joensuu.fi/sipu/datasets/pathbased.txt"""

# Importação das bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import rand_score

# Configurações. Aqui coloquei k variando entre 2 a 6, pois sabemos que o ideal são 3 grupos, mas quis que o algoritmo decidisse isso.
url = "http://cs.joensuu.fi/sipu/datasets/pathbased.txt"
valores_k = [2, 3, 4, 5, 6]
limiar_convergencia = 0.0001

# Carregamento dos dados ignorando a terceira coluna, pois aqui o aprendizado é não supervisionado.
df = pd.read_csv(url, sep= r'\s+', header=None)
X = df.iloc[:, [0, 1]].values
y_real = df.iloc[:, 2].values

# Variáveis para lembrar o melhor resultado de cada algoritmo
melhor_k_kmeans = 0
melhor_nota_kmeans = -1
melhores_labels_kmeans = []

melhor_k_single = 0
melhor_nota_single = -1
melhores_labels_single = []

# Testa todos os valores de k para ambos os algoritmos
for k in valores_k:

    kmeans = KMeans(n_clusters=k, tol=limiar_convergencia, random_state=42)
    labels_km = kmeans.fit_predict(X)
    nota_km = rand_score(y_real, labels_km)

    # Se a nota atual for maior que a nota guardada, atualizamos a memória
    if nota_km > melhor_nota_kmeans:
        melhor_nota_kmeans = nota_km
        melhor_k_kmeans = k
        melhores_labels_kmeans = labels_km

    single_linkage = AgglomerativeClustering(n_clusters=k, linkage='single')
    labels_sg = single_linkage.fit_predict(X)
    nota_sg = rand_score(y_real, labels_sg)

    # Se a nota atual for maior que a nota guardada, atualizamos a memória
    if nota_sg > melhor_nota_single:
        melhor_nota_single = nota_sg
        melhor_k_single = k
        melhores_labels_single = labels_sg

# Exibe os melhores resultados para o k encontrado
print("Melhor resultado:")
print(f"K-Means (Melhor K = {melhor_k_kmeans}):        {melhor_nota_kmeans:.4f}")
print(f"Single Linkage (Melhor K = {melhor_k_single}): {melhor_nota_single:.4f}")
print("-------------------------------------------")

# Plota os gráficos que obtiveram os melhores resultados para cada algoritmo
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))


ax1.scatter(X[:, 0], X[:, 1], c=melhores_labels_kmeans, cmap='viridis', s=15)
ax1.set_title(f"K-Means (K={melhor_k_kmeans}) | Índice Rand: {melhor_nota_kmeans:.2f}")
ax1.set_xlabel("Eixo X")
ax1.set_ylabel("Eixo Y")


ax2.scatter(X[:, 0], X[:, 1], c=melhores_labels_single, cmap='plasma', s=15)
ax2.set_title(f"Single Linkage (K={melhor_k_single}) | Índice Rand: {melhor_nota_single:.2f}")
ax2.set_xlabel("Eixo X")
ax2.set_ylabel("Eixo Y")

plt.show()

"""Testando para k fixado como 3"""

# Importação das bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import rand_score

# Configurações. Aqui coloquei k variando entre 2 a 6, pois sabemos que o ideal são 3 grupos, mas quis que o algoritmo decidisse isso.
url = "http://cs.joensuu.fi/sipu/datasets/pathbased.txt"
valores_k = [3]
limiar_convergencia = 0.0001

# Carregamento dos dados ignorando a terceira coluna, pois aqui o aprendizado é não supervisionado.
df = pd.read_csv(url, sep= r'\s+', header=None)
X = df.iloc[:, [0, 1]].values
y_real = df.iloc[:, 2].values

# Variáveis para lembrar o melhor resultado de cada algoritmo
melhor_k_kmeans = 0
melhor_nota_kmeans = -1
melhores_labels_kmeans = []

melhor_k_single = 0
melhor_nota_single = -1
melhores_labels_single = []

# Testa todos os valores de k para ambos os algoritmos
for k in valores_k:

    kmeans = KMeans(n_clusters=k, tol=limiar_convergencia, random_state=42)
    labels_km = kmeans.fit_predict(X)
    nota_km = rand_score(y_real, labels_km)

    # Se a nota atual for maior que a nota guardada, atualizamos a memória
    if nota_km > melhor_nota_kmeans:
        melhor_nota_kmeans = nota_km
        melhor_k_kmeans = k
        melhores_labels_kmeans = labels_km

    single_linkage = AgglomerativeClustering(n_clusters=k, linkage='single')
    labels_sg = single_linkage.fit_predict(X)
    nota_sg = rand_score(y_real, labels_sg)

    # Se a nota atual for maior que a nota guardada, atualizamos a memória
    if nota_sg > melhor_nota_single:
        melhor_nota_single = nota_sg
        melhor_k_single = k
        melhores_labels_single = labels_sg

# Exibe os melhores resultados para o k encontrado
print("Melhor resultado:")
print(f"K-Means (Melhor K = {melhor_k_kmeans}):        {melhor_nota_kmeans:.4f}")
print(f"Single Linkage (Melhor K = {melhor_k_single}): {melhor_nota_single:.4f}")
print("-------------------------------------------")

# Plota os gráficos que obtiveram os melhores resultados para cada algoritmo
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))


ax1.scatter(X[:, 0], X[:, 1], c=melhores_labels_kmeans, cmap='viridis', s=15)
ax1.set_title(f"K-Means (K={melhor_k_kmeans}) | Índice Rand: {melhor_nota_kmeans:.2f}")
ax1.set_xlabel("Eixo X")
ax1.set_ylabel("Eixo Y")


ax2.scatter(X[:, 0], X[:, 1], c=melhores_labels_single, cmap='plasma', s=15)
ax2.set_title(f"Single Linkage (K={melhor_k_single}) | Índice Rand: {melhor_nota_single:.2f}")
ax2.set_xlabel("Eixo X")
ax2.set_ylabel("Eixo Y")

plt.show()

"""Para o dataset: http://cs.joensuu.fi/sipu/datasets/flame.txt"""

# Importação das bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import rand_score

# Configurações. Aqui coloquei k variando entre 2 a 6, pois sabemos que o ideal são 2 grupos, mas quis que o algoritmo decidisse isso.
url = "http://cs.joensuu.fi/sipu/datasets/flame.txt"
valores_k = [2, 3, 4, 5, 6]
limiar_convergencia = 0.0001

# Carregamento dos dados ignorando a terceira coluna, pois aqui o aprendizado é não supervisionado.
df = pd.read_csv(url, sep= r'\s+', header=None)
X = df.iloc[:, [0, 1]].values
y_real = df.iloc[:, 2].values

# Variáveis para lembrar o melhor resultado de cada algoritmo
melhor_k_kmeans = 0
melhor_nota_kmeans = -1
melhores_labels_kmeans = []

melhor_k_single = 0
melhor_nota_single = -1
melhores_labels_single = []

# Testa todos os valores de k para ambos os algoritmos
for k in valores_k:

    kmeans = KMeans(n_clusters=k, tol=limiar_convergencia, random_state=42)
    labels_km = kmeans.fit_predict(X)
    nota_km = rand_score(y_real, labels_km)

    # Se a nota atual for maior que a nota guardada, atualizamos a memória
    if nota_km > melhor_nota_kmeans:
        melhor_nota_kmeans = nota_km
        melhor_k_kmeans = k
        melhores_labels_kmeans = labels_km

    single_linkage = AgglomerativeClustering(n_clusters=k, linkage='single')
    labels_sg = single_linkage.fit_predict(X)
    nota_sg = rand_score(y_real, labels_sg)

    # Se a nota atual for maior que a nota guardada, atualizamos a memória
    if nota_sg > melhor_nota_single:
        melhor_nota_single = nota_sg
        melhor_k_single = k
        melhores_labels_single = labels_sg

# Exibe os melhores resultados para o k encontrado
print("Melhor resultado:")
print(f"K-Means (Melhor K = {melhor_k_kmeans}):        {melhor_nota_kmeans:.4f}")
print(f"Single Linkage (Melhor K = {melhor_k_single}): {melhor_nota_single:.4f}")
print("-------------------------------------------")

# Plota os gráficos que obtiveram os melhores resultados para cada algoritmo
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))


ax1.scatter(X[:, 0], X[:, 1], c=melhores_labels_kmeans, cmap='viridis', s=15)
ax1.set_title(f"K-Means (K={melhor_k_kmeans}) | Índice Rand: {melhor_nota_kmeans:.2f}")
ax1.set_xlabel("Eixo X")
ax1.set_ylabel("Eixo Y")


ax2.scatter(X[:, 0], X[:, 1], c=melhores_labels_single, cmap='plasma', s=15)
ax2.set_title(f"Single Linkage (K={melhor_k_single}) | Índice Rand: {melhor_nota_single:.2f}")
ax2.set_xlabel("Eixo X")
ax2.set_ylabel("Eixo Y")

plt.show()

"""
Testando para k=2.
> Adicionar aspas

"""

# Importação das bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import rand_score

# Configurações. Aqui coloquei k variando entre 2 a 6, pois sabemos que o ideal são 2 grupos, mas quis que o algoritmo decidisse isso.
url = "http://cs.joensuu.fi/sipu/datasets/flame.txt"
valores_k = [2]
limiar_convergencia = 0.0001

# Carregamento dos dados ignorando a terceira coluna, pois aqui o aprendizado é não supervisionado.
df = pd.read_csv(url, sep= r'\s+', header=None)
X = df.iloc[:, [0, 1]].values
y_real = df.iloc[:, 2].values

# Variáveis para lembrar o melhor resultado de cada algoritmo
melhor_k_kmeans = 0
melhor_nota_kmeans = -1
melhores_labels_kmeans = []

melhor_k_single = 0
melhor_nota_single = -1
melhores_labels_single = []

# Testa todos os valores de k para ambos os algoritmos
for k in valores_k:

    kmeans = KMeans(n_clusters=k, tol=limiar_convergencia, random_state=42)
    labels_km = kmeans.fit_predict(X)
    nota_km = rand_score(y_real, labels_km)

    # Se a nota atual for maior que a nota guardada, atualizamos a memória
    if nota_km > melhor_nota_kmeans:
        melhor_nota_kmeans = nota_km
        melhor_k_kmeans = k
        melhores_labels_kmeans = labels_km

    single_linkage = AgglomerativeClustering(n_clusters=k, linkage='single')
    labels_sg = single_linkage.fit_predict(X)
    nota_sg = rand_score(y_real, labels_sg)

    # Se a nota atual for maior que a nota guardada, atualizamos a memória
    if nota_sg > melhor_nota_single:
        melhor_nota_single = nota_sg
        melhor_k_single = k
        melhores_labels_single = labels_sg

# Exibe os melhores resultados para o k encontrado
print("Melhor resultado:")
print(f"K-Means (Melhor K = {melhor_k_kmeans}):        {melhor_nota_kmeans:.4f}")
print(f"Single Linkage (Melhor K = {melhor_k_single}): {melhor_nota_single:.4f}")
print("-------------------------------------------")

# Plota os gráficos que obtiveram os melhores resultados para cada algoritmo
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))


ax1.scatter(X[:, 0], X[:, 1], c=melhores_labels_kmeans, cmap='viridis', s=15)
ax1.set_title(f"K-Means (K={melhor_k_kmeans}) | Índice Rand: {melhor_nota_kmeans:.2f}")
ax1.set_xlabel("Eixo X")
ax1.set_ylabel("Eixo Y")


ax2.scatter(X[:, 0], X[:, 1], c=melhores_labels_single, cmap='plasma', s=15)
ax2.set_title(f"Single Linkage (K={melhor_k_single}) | Índice Rand: {melhor_nota_single:.2f}")
ax2.set_xlabel("Eixo X")
ax2.set_ylabel("Eixo Y")

plt.show()